# Generated by Django 4.2.7 on 2025-12-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
