# Generated by Django 4.2.7 on 2025-12-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_milestone_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='escrow_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='onchain_project_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
