# Generated by Django 4.2.7 on 2025-12-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_created_tx_hash_project_escrow_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chain_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deployment_wallet_type',
            field=models.CharField(blank=True, choices=[('metamask', 'MetaMask'), ('local', 'Local Wallet')], max_length=20, null=True),
        ),
    ]
