# Generated by Django 4.2.7 on 2025-12-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_chain_id_project_deployment_wallet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='onchain_milestone_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of milestone on blockchain', null=True),
        ),
    ]
