# Generated by Django 4.2.7 on 2025-11-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='release',
            name='released_to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='finance.wallet'),
        ),
        migrations.AddField(
            model_name='refund',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='refund',
            name='pledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='finance.pledge'),
        ),
    ]
