# Generated by Django 5.2.8 on 2025-11-29 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('escrow_address', models.CharField(max_length=255)),
                ('funding_goal', models.DecimalField(decimal_places=18, max_digits=38)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('backer_address', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=38)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('pledged_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexer.project')),
            ],
            options={
                'db_table': 'pledges',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('percentage', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexer.project')),
            ],
            options={
                'db_table': 'milestones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=38)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('refunded_at', models.DateTimeField()),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexer.pledge')),
            ],
            options={
                'db_table': 'refunds',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=38)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('released_at', models.DateTimeField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexer.milestone')),
            ],
            options={
                'db_table': 'releases',
                'managed': True,
            },
        ),
    ]
