# Generated by Django 4.2.7 on 2026-01-08 23:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Backer',
            fields=[
                ('backer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('total_pledged', models.DecimalField(decimal_places=18, default=0, max_digits=38)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('milestone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_amount', models.DecimalField(db_column='funding_amount', decimal_places=18, default=0, max_digits=38)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('on_chain_id', models.IntegerField(blank=True, null=True)),
                ('voting_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'milestones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('pledge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=38)),
                ('transaction_hash', models.CharField(max_length=255, null=True, unique=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('voting_power', models.DecimalField(decimal_places=18, default=0, max_digits=38)),
                ('pledged_at', models.DateTimeField()),
                ('backer', models.ForeignKey(db_column='backer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='indexer.backer')),
            ],
            options={
                'db_table': 'pledges',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('escrow_address', models.CharField(max_length=255)),
                ('creator_address', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_goal', models.DecimalField(decimal_places=18, max_digits=38)),
                ('total_pledged', models.DecimalField(decimal_places=18, default=0, max_digits=38)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(max_length=64)),
                ('on_chain_id', models.IntegerField(null=True, unique=True)),
                ('created_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255, unique=True)),
                ('last_processed_block', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sync_state',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval', models.IntegerField()),
                ('vote_weight', models.DecimalField(decimal_places=18, default=1, max_digits=38)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('backer', models.ForeignKey(db_column='backer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='indexer.backer')),
                ('milestone', models.ForeignKey(db_column='milestone_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='indexer.milestone')),
            ],
            options={
                'db_table': 'votes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=38)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('released_at', models.DateTimeField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexer.milestone')),
            ],
            options={
                'db_table': 'releases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=38)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('refunded_at', models.DateTimeField()),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indexer.pledge')),
            ],
            options={
                'db_table': 'refunds',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, to='indexer.project'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='indexer.project'),
        ),
    ]
