# Generated by Django 5.2.8 on 2025-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='on_chain_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
