# Generated by Django 5.2.8 on 2025-12-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_milestone_is_activated_milestone_on_chain_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('backer_address', models.CharField(max_length=255)),
                ('decision', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=18, default=1, max_digits=38)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='indexer.milestone')),
            ],
            options={
                'db_table': 'votes',
                'managed': True,
                'unique_together': {('milestone', 'backer_address')},
            },
        ),
    ]
