# Generated by Django 5.2.8 on 2025-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
