# Generated by Django 5.2.8 on 2025-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0004_project_creator_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_pledged',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=38),
        ),
    ]
