# Generated by Django 5.2.8 on 2025-12-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0005_project_total_pledged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='percentage',
        ),
        migrations.AddField(
            model_name='milestone',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='funded_amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=38),
        ),
        migrations.AddField(
            model_name='milestone',
            name='required_amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=38),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.project'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(default='pending', max_length=64),
        ),
    ]
