# Generated by Django 5.0.6 on 2025-12-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0006_remove_milestone_percentage_milestone_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255, unique=True)),
                ('last_processed_block', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sync_state',
                'managed': True,
            },
        ),
        # migrations.AddField(
        #     model_name='milestone',
        #     name='transaction_hash',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='milestone',
        #     name='voting_session_id',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='pledge',
        #     name='block_number',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='pledge',
        #     name='status',
        #     field=models.CharField(default='confirmed', max_length=64),
        # ),
        # migrations.AddField(
        #     model_name='project',
        #     name='created_tx_hash',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='project',
        #     name='on_chain_id',
        #     field=models.IntegerField(null=True, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='pledge',
        #     name='transaction_hash',
        #     field=models.CharField(max_length=255, unique=True),
        # ),
    ]
