# Generated by Django 4.2.7 on 2025-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_type',
            field=models.CharField(blank=True, choices=[('metamask', 'MetaMask'), ('local', 'Local Wallet')], max_length=20, null=True),
        ),
    ]
